### PR TITLE
If egulias/email-validator bundle exists then use EmailValidator for …

### PR DESCRIPTION
**Pull request by ashutoshsilverline**
…swiftmailer to validate address in MailBoxHeader

### CODE REVIEW

**Comment by stof** [comment]
The 5.x version of Swiftmailer is still compatible with PHP 5.2, and this will trigger syntax errors on 5.2.

The 6.x dev version of Swiftmailer (i.e. the master branch) already uses this library.

**Comment by Nek-** [comment]
Btw @stof this lib is not as good as is the current check of Swiftmailer. :/

But this PR is definitively wrong.

**Comment by ashutoshsilverline** [comment]
Hi @stof, Actually swiftmailer is not supporting accent. so that's why used EmailValidator if exists.

**Comment by Nek-** [comment]
`mélanie@free.fr` is not valid.

`melanie@méninge.fr` is valid.

Swiftmailer is ok with that.

**Comment by ashutoshsilverline** [comment]
Address in mailbox given [ashutosh@gmailé.com] does not comply with RFC 2822, 3.6.2.
500 Internal Server Error - Swift_RfcComplianceException
2:39
in vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php at line 356  -

**Comment by ashutoshsilverline** [comment]
Address in mailbox given [melanie@méninge.fr] does not comply with RFC 2822, 3.6.2.
500 Internal Server Error - Swift_RfcComplianceException 
in vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php at line 356 -

**Comment by Nek-** [comment]
@ashutoshsilverline this is fixed in swiftmailer 6.x (thanks to usage of another validator).

But there is still a problem as the validator doesn't detect `mélanie@free.fr` as wrong.

Please close this issue that is not accurate, the problem is on another project now.

**Pull request closed without merging**
