### PR TITLE
#403 - Use of EmailValidator for versions of PHP >= 5.3

### PR DESCRIPTION
**Pull request by egulias**
See #403
I've not found a way to create a bridge class for using the EmailValidator in PHP 5.2 because of the namespaces. This fix allows for the use of the lib if you are using PHP 5.3 and leaves the usage of the previous validation otherwise.

### CODE REVIEW

**Comment by egulias** [comment]
We turned a year since I began this PR :)!!
@fabpot how can I help to move this forward (even if other PR should be done)
Thanks.

**Comment by egulias** [comment]
Hi again!
Is there any way to help to move this forward?

**Comment by sstok** [comment]
@fabpot @stof ping

**Comment by dstevenson** [comment]
What are the remaining issues here blocking a merge?

**Comment by dstevenson** [comment]
@fabpot @stof 

Did either of you have a chance to review the latest changes here?

**Comment by fabpot** [comment]
Thank you @egulias.

**Comment by fabpot** [comment]
This pul request is the first one to be merged into the newly created 6.0 version (which is now the master branch.)

**Comment by Maxooo** [comment]
:+1:

**Comment by notrix** [comment]
:+1:

**Comment by acasademont** [comment]
any updates on the 6.0 branch? thanks!

**Comment by acrobat** [comment]
@fabpot do you have an idea when version 6 could get a release?

**Comment by tadcka** [comment]
@fabpot planned release 6 version?

**Comment by acrobat** [comment]
Ping @fabpot is there a ETA for V6 or a todo list so we can help?

**Comment by dstevenson** [comment]
@fabpot the lack of response to this issue is wearisome. If you're no longer able to maintain this project then we need to find someone who can. This is holding up a lot of people.

**Comment by fabpot** [comment]
@dstevenson Who ever said that I would be the only one contributing to this project? Do you volunteer? Because I could obviously use some help here.

**Comment by dstevenson** [comment]
@fabpot Great. Take a look at the above comments for the past 2 years and you'll see lots of people trying to lend their hand and met with silence. It's not clear the direction you're trying to take the project with respect to a version 6, and so far you've been actively avoiding everyone who is trying to collaborate with you on this.

**Pull request closed without merging**
