### PR TITLE
use LF instead of CRLF for wider compatibility

### LINKED ISSUE #393: Break in long headers leads to a broken subject-line
We experienced problems with a broken subject-line. Judging from reports from mail-recipients (which we weren't yet able to reproduce) it seems to after such an "invalid" header some email-programs seem to parse the rest of the header as part of the email-body leading to various other "funny" bugs. Using Thunderbird etc. I did not experience any problems.
Investigating further into this brought me to a subject-line like:

Subject: Winterfest 2013 - Das Spiegelzelt kehrt nach Salzburg =?utf-8?Q?zorr?=^M
 =?utf-8?Q?rrr=C3=BCck?=

Notice the ^M which "vim" displays (and went unnoticed in other tools). I noticed that at this point the linux comandline "mail"-utility also shows a space-character in the subject-line, right in the middle of a word. This is the only header that contains a ^M and removing it this for example fixes the problem with "mail".

We experienced the problem with SwiftMailer 4.0.x (shipped with current TYPO3 4.5.30 LTS-release) but also tested it exists equally throughout the 4.x-releases including the latest 4.3.1. I couldn't yet test this on 5.x.

Fix: in classes/Swift/Mime/Headers/AbstractHeader.php in getTokenAsEncodedWord() change
return implode("\r\n ", $encodedTextLines);
to just
return implode("\n ", $encodedTextLines);

Since the \r\n is expected in various parts of the encoding before imho this "fix" late in the chain here looks like the best solution.

I expect this might also be related to bug-reports like #185.

### PR DESCRIPTION
**Pull request by MorrisJobke**
* fixes #393 
* fails with postfix on CentOS 6 otherwise

Fix is from #549 - Hopefully fix the tests that are failing in #549

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Or maybe `PHP_EOL` should be used? http://stackoverflow.com/a/6360550

> Postfix expects EOL to be LF when picking up mail from sendmail on unix and replaces that with CRLF when sending. When it gets CRLF it still replaces the LF and we get CRCRLF.

**Comment by MorrisJobke** [comment]
This would explain the seen behavior. Maybe Swiftmail should use LF if it uses sendmail with postfix :see_no_evil:

**Comment by GrahamCampbell** [comment]
> Or maybe PHP_EOL should be used?

That would lead to inconstant behaviour across platforms.

**Comment by MorrisJobke** [comment]
@GrahamCampbell Do you have a good idea how to fix the broken behavior on postfix?

**Comment by GrahamCampbell** [comment]
Hmmm, maybe just change the implode statement?

**Comment by MorrisJobke** [comment]
> Hmmm, maybe just change the implode statement?

To what?

**Comment by sstok** [comment]
Headers must follow the standards, which require the usage of CRLF!
https://tools.ietf.org/html/rfc5322#section-2.2

> Header fields are lines beginning with a field name, followed by a
   colon (":"), followed by a field body, and terminated by **CRLF**.

If Sendmail expects something else, the sendmail transporter should be fixed instead.

**Comment by MorrisJobke** [comment]
It turns out that the is an issue with the sendmail version -> close

**Pull request closed without merging**
