### PR TITLE
Don't trust properties at destruct time

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Doc update?   | no
| BC breaks?    | yes
| Deprecations? | no
| Fixed tickets | -
| License       | MIT

Prevent destructors with side-effects from being unserialized

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @jderusse.

**Comment by jderusse** [comment]
Thank you @nicolas-grekas for the patch.

**Comment by pperzyna** [comment]
@jderusse @fabpot What is wrong with deserialization? It is a common practice and even more important for emails that are in a queue!

**Comment by jderusse** [comment]
this is can be abused by attacker. See https://owasp.org/www-community/vulnerabilities/PHP_Object_Injection

**Comment by jderusse** [comment]
> more important for emails that are in a queue!

Messages are serializable. Transport and Temporary streams are not (and, they never should have been serialized)

**Pull request merged**
