### PR TITLE
new static to new self fix

### PR DESCRIPTION
**Pull request by htonus**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Why so many PRs?

**Comment by stof** [comment]
@GrahamCampbell because he is doing them from the web UI

**Comment by GrahamCampbell** [comment]
@stof What does this actually fix?

**Comment by KorsaR-ZN** [comment]
@GrahamCampbell :+1:

**Comment by stof** [comment]
the only idea I have is that this would fix compatibility with PHP 5.2. but Swiftmailer bumped the min requirement to 5.3.3, so I don't see any valid reason for this change.

**Comment by KorsaR-ZN** [comment]
I think it doesn't need merge

**Comment by GrahamCampbell** [comment]
:-1:

**Pull request closed without merging**
