### PR TITLE
[doc] fix missing bracket

### LINKED ISSUE #940: Having a strange error "unexpected '->' (T_OBJECT_OPERATOR)"
Hi! Help me please with this strange thing.

Using this code:
```
require_once __DIR__.'/lib/swift_required.php';

$transport = new Swift_SmtpTransport('localhost', 25);

$mailer = new Swift_Mailer($transport);

$message = new Swift_Message("Обратная связь с сайта ManeQuest! $language")
	->setFrom(['info@timlion.ru' => 'ManeQuest'])
	->setTo(['tim@timlion.ru'])
	->setBody("Тема: $theme<br>e-mail: $email<br>Текст: $text<br>Имя/ник: $nickname")
	->setContentType('text/html');
```

End server respondes an error to me:
> Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in ... on line 45

This line is 
`->setFrom(['info@timlion.ru' => 'ManeQuest'])`

I'm looking to this and i don't know how to fix it for 4 hours. My brains are hot.

### PR DESCRIPTION
**Pull request by Rotzbua**
fix #940

### CODE REVIEW

**Comment by fabpot** [comment]
Good catch, thanks @Rotzbua.

**Comment by TimurGumarov** [comment]
Hi!
This problem in documentation here too:
http://swiftmailer.org/docs/sending.html#using-the-send-method

**Comment by Rotzbua** [comment]
@TimurGumarov Can you make a pull request? Just change https://github.com/swiftmailer/swiftmailer/blob/master/doc/sending.rst . Thanks!

**Comment by TimurGumarov** [comment]
#944

**Comment by TimurGumarov** [comment]
#944

**Comment by TimurGumarov** [comment]
fix #944

**Pull request merged**
